config/routes.rb
Rails.application.routes.draw do

  #get '/products/index', to: 'products#index'
  #get '/products/new', to: 'products#new_path'
  #post 'products/create', to: 'products#create'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  		redirect_to products_path, notice: "El producto fue publicado con éxito"
  	else 
  		render :new
  	end
  end

  def show
  	@product = Product.find(params[:id])
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def update
  	product = Product.find(params[:id])
  	if product.update(product_params)
  		redirect_to products_path, notice: "El producto ha sido modificado con éxito"
  	else
  		render :edit
  	end
  end

  def destroy
  	product = Product.find(params[:id])
  	product.destroy

  	redirect_to products_path, notice: "El producto fue eliminado con éxito"
  end

  private 
  	def product_params
  	 	params.require(:product).permit(:name, :url, :descripcion)
  	 end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def form_title
		@product.new_record? ? "Publicar Producto" : "Modificar Producto"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Producthunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if flash[:notice] %>
  		<div class="alert alert-info"><%= flash[:notice] %></div>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1><%= form_title %></h1>
			<%= form_for @product do |f|  %>
				<div class="form-group">
					<%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del producto" %>
				</div>

				<div class="form-group">
					<%= f.url_field :url, class: "form-control input-lg", placeholder: "Ingresa la url del producto" %>
				</div>

				<div class="form-group">
					<%= f.text_area :descripcion, class: "form-control input-lg", placeholder: "Ingresa la descripción del producto" %>
				</div>

				<div>
					<%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Productos</h1>

      <div class="text-center">
        <%= link_to "Publicar producto", new_product_path, class: "btn btn-primary " %>
      </div>

      <table class="table">
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>URL</th>
          <th>Descripción</th>
        </tr>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= link_to product.name, product %></td>
            <td><%= product.url %></td>
            <td><%= product.descripcion %></td>
            <td>
              <%= link_to "Editar", edit_product_path(product) %>
              <%= link_to "Eliminar", product, method: :delete, data: { confirm: "¿Está seguro de eliminar este producto"} %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1>Publicar Producto</h1>
			<%= form_for @product do |f|  %>
				<div class="form-group">
					<%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del producto" %>
				</div>

				<div class="form-group">
					<%= f.url_field :url, class: "form-control input-lg", placeholder: "Ingresa la url del producto" %>
				</div>

				<div class="form-group">
					<%= f.text_area :descripcion, class: "form-control input-lg", placeholder: "Ingresa la descripción del producto" %>
				</div>

				<div>
					<%= f.submit "Publicar producto", class: "btn btn-primary btn-lg btn-block" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h1><%= @product.name %></h1>
			<p><%= @product.descripcion %></p>
			<a href="<%= @product.url %>" target="_blank">¡Obtenlo!</a>
		</div>
	</div>
</div>